### ISSUE TITLE
Hey! Firstly: Thanks!

### ISSUE THREAD

**Issue by knezmej** [mildsunrise/ccv15#2]
Using http://nuigc.com/?go=https://github.com/downloads/jmendeth/ccv15/CCV-1.5-lin-prev-alpha-i368.zip
that You posted 01 August 2012 02:45 PM on http://nuigroup.com/forums/viewthread/13330/P165/

I found bug on Ubuntu 12.10 64 bit:
error while loading shared libraries: libglut.so.3: cannot open shared object file: No such file or directory

I have found this file in /usr/lib32/i386-linux-gnu and in /usr/lib/x86_64-linux-gnu, but I don't know where I have to symlink it.
I'll be thankful for Your time and help.

**Comment by mildsunrise** [comment]
Thanks for the :+1:,

this problem you're experiencing is actually not a bug, but a missing library.
It can also be because you're using a **32-bit** build on a **64-bit** OS.
